feature : iphone se camera setting
mash-up-kr/Pream-iOS pull request #74
Opened 2019-03-24 16:13 UTC by SujiKim6

아이폰 SE 실단말기에서 실행했을 때 앱 죽는 부분 해결

2019-03-25 07:48 UTC, JeaSungLEE commented on pream/Extension/UIDevice+GetDeviceModel.swift
> +            #elseif os(tvOS)
얘는 빼도 될것같은데요

2019-03-25 07:49 UTC, JeaSungLEE requested changes

2019-03-25 07:49 UTC, JeaSungLEE commented on pream/Extension/UIDevice+GetDeviceModel.swift
> +public extension UIDevice {
왜 굳이 public으로 만들었는가여

2019-03-26 15:48 UTC, SujiKim6 commented on pream/Extension/UIDevice+GetDeviceModel.swift
> +            #elseif os(tvOS)
제거했습니다~

2019-03-26 15:48 UTC, SujiKim6 commented on pream/Extension/UIDevice+GetDeviceModel.swift
> +public extension UIDevice {
그러게여... 다시보니 굳이 필요가 없네요ㅎㅎ..
제거했습니다~~

2019-03-27 05:45 UTC, JeaSungLEE approved these changes

2019-03-27 07:46 UTC, merged